name: Jenkins Security Scan
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  security-scan:
    uses: daniel-beck-org/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@v1
