name: Jenkins Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  security-scan:
    uses: daniel-beck-org/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@main # TODO Migrate
